management:
    endpoints:
        web:
            exposure:
                include: "*"
---
spring:
    profiles: default
    web.resources.static-locations: "file:./app"
cds:
    odata-v4:
        endpoint:
            path: "/"

server:
    port: 4004

---
spring:
    profiles: cloud

cds:
    odata-v4:
        endpoint:
            path: "/"
